### ISSUE TITLE
Make Bitcoin donation address a link to a block explorer

### ISSUE THREAD

**Issue by abrkn** [Chr12t0pher/r-slash-thebutton#1]
...or it's way too much work to get a QR code for it to scan with phone

**Comment by orawalters** [comment]
Could we get the donation page included in the source code? Unless I missed something it's been removed and I could totally do this.

**Comment by Chr12t0pher** [comment]
Both issues addressed in 58bb1c159ae15e0bab595d441a6faef94547d68d
